# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(269, 231)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 241, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label.setObjectName("label")
        self.sort = QtWidgets.QLineEdit(Form)
        self.sort.setGeometry(QtCore.QRect(120, 20, 113, 22))
        self.sort.setObjectName("sort")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 55, 16))
        self.label_6.setObjectName("label_6")
        self.prozh = QtWidgets.QLineEdit(Form)
        self.prozh.setGeometry(QtCore.QRect(120, 50, 113, 22))
        self.prozh.setObjectName("prozh")
        self.sost = QtWidgets.QLineEdit(Form)
        self.sost.setGeometry(QtCore.QRect(120, 80, 113, 22))
        self.sost.setObjectName("sost")
        self.vkus = QtWidgets.QLineEdit(Form)
        self.vkus.setGeometry(QtCore.QRect(120, 110, 113, 22))
        self.vkus.setObjectName("vkus")
        self.cost = QtWidgets.QLineEdit(Form)
        self.cost.setGeometry(QtCore.QRect(120, 140, 113, 22))
        self.cost.setObjectName("cost")
        self.value = QtWidgets.QLineEdit(Form)
        self.value.setGeometry(QtCore.QRect(120, 170, 113, 22))
        self.value.setObjectName("value")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.label.setText(_translate("Form", "Сорт"))
        self.label_2.setText(_translate("Form", "Прожарка"))
        self.label_3.setText(_translate("Form", "Состояние"))
        self.label_4.setText(_translate("Form", "Вкус"))
        self.label_5.setText(_translate("Form", "Цена"))
        self.label_6.setText(_translate("Form", "Объём"))
